### ISSUE TITLE
Limit the address families used

### ISSUE THREAD

**Issue by xorrkaz** [fenner/probe-clarification#3]
This document describes that when the L bit is not set, one can specify an interface address using:

>All values found in the IANA registry of Address Family Numbers (available from [[IANA.address-family-numbers](http://www.iana.org/assignments/address-family-numbers)]) are valid in this field.

However, in Section 1, it is mentioned that resolution for a non-local address will be done using either ARP or NDP table lookups.  While IPv4, IPv6, and MAC can be found in these tables, other AFIs may not be.  As such, I think the text should be limited to AFIs for IPv4, IPv6, and 48-bit MAC alone.  Any other AFI would result in a malformed message as the lookup cannot be performed.  

Alternatively, if other lookups could be supported, that could be described here or simply left for other extension documents that might update this document.

**Comment by fenner** [comment]
Thanks for bringing this up, Joe.  [Section 4.1](https://fenner.github.io/probe-clarification/draft-fenner-intarea-probe-clarification.html#name-code-field-processing) says:

> The Code field MUST be set to (3) No Such Table Entry if the L-bit
> is clear and the address found in the Interface Identification Object
> does not appear in the IPv4 Address Resolution Protocol (ARP) table or
> the IPv6 Neighbor Cache.

In my mind, this is sufficient - if you set the AF to IPX, and that IPX address doesn't appear in the IPv4 ARP or IPv6 neighbor cache (hint: it can't), then you return No Such Table Entry - so we have a well defined behavior in the "arbitrary AF" case.

If we try to go down the path of limiting this in the address field specification, we end up having to differentiate based on the setting of the L bit - since it's actually valid to ask about the interface with IPX address foo if L=1.

**Comment by xorrkaz** [comment]
I think the "No Such Table Entry" error is fine in this case.
